---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: m3demo
  namespace: m3test
spec:
  secretName: m3demo-cert
  issuerRef:
    name: letsencrypt-docnetwork
    kind: ClusterIssuer
  dnsNames:
    - "*.m3test.doc.network"
    - "*.m3demo.doc.network"
